// 设计语言/src/components/SectionHeading/index.tsx
import React from 'react';

export type SectionHeadingTone = 'light' | 'dark';

export interface SectionHeadingProps {
  /** Small tabular index shown before the label (e.g. "01"). Optional — omit for editorial-warm screens. */
  index?: string;
  /** Short section label rendered next to the hairline. */
  label?: string;
  /** Section title. `children` takes precedence when provided. */
  title?: string;
  /** Supporting copy under the title. */
  description?: string;
  /** `dark` inverts ink colours for use on dark photography / dark bands. */
  tone?: SectionHeadingTone;
  /** Trailing action slot (link or button), bottom-aligned with the title block. */
  action?: React.ReactNode;
  /** Heading element, so the section keeps a correct document outline. */
  as?: 'h1' | 'h2' | 'h3' | 'h4';
  /** Title content — overrides `title`. */
  children?: React.ReactNode;
  className?: string;
}

export function SectionHeading({
  index = '',
  label = '',
  title = '',
  description = '',
  tone = 'light',
  action,
  as: Heading = 'h2',
  children,
  className = ''
}: SectionHeadingProps) {
  const isDark = tone === 'dark';
  const hasMeta = Boolean(index || label);

  return (
    <div
      className={[
      'block mb-6',
      'min-[721px]:flex min-[721px]:flex-wrap min-[721px]:items-end min-[721px]:justify-between',
      'min-[721px]:gap-x-6 min-[721px]:gap-y-10 min-[721px]:mb-12',
      className].

      filter(Boolean).
      join(' ')}>
      
      <div className="max-w-[640px]">
        {hasMeta &&
        <div className="flex items-center gap-3">
            {index &&
          <span
            data-numeric="true"
            className={`text-[12px] tabular-nums ${isDark ? 'text-white/50' : 'text-muted'}`}>
            
                {index}
              </span>
          }
            <span
            aria-hidden="true"
            className={`h-px w-6 ${isDark ? 'bg-white/25' : 'bg-line'}`} />
          
            {label &&
          <span
            className={`text-[13px] font-medium ${isDark ? 'text-white/50' : 'text-ink-soft'}`}>
            
                {label}
              </span>
          }
          </div>
        }

        <Heading
          className={[
          'font-display font-normal leading-[1.15] tracking-[-0.045em] [text-wrap:balance]',
          'text-[28px] min-[721px]:text-[clamp(28px,3.4vw,42px)]',
          hasMeta ? 'mt-4' : 'mt-0',
          isDark ? 'text-cream' : 'text-ink'].
          join(' ')}>
          
          {children ?? title}
        </Heading>

        {description &&
        <p
          className={[
          'mt-3 min-[721px]:mt-4 max-w-[560px] text-[15px] leading-[1.65]',
          isDark ? 'text-white/55' : 'text-ink-soft opacity-80'].
          join(' ')}>
          
            {description}
          </p>
        }
      </div>

      {action &&
      <div className="mt-3 shrink-0 min-[721px]:mt-0 min-[721px]:pb-1">{action}</div>
      }
    </div>);

}

// frontend/src/components/dashboard/SectionHeading.vue
<template>
  <div class="sh-wrap">
    <div class="sh-left">
      <div class="sh-meta">
        <span class="sh-idx">{{ index }}</span>
        <span class="sh-line" aria-hidden="true"></span>
        <span class="sh-lbl" :class="{ 'sh-lbl-dark': tone === 'dark' }">{{ label }}</span>
      </div>
      <h2 class="sh-title" :class="{ 'sh-title-dark': tone === 'dark' }">
        <slot>{{ title }}</slot>
      </h2>
      <p v-if="description" class="sh-desc" :class="{ 'sh-desc-dark': tone === 'dark' }">
        {{ description }}
      </p>
    </div>
    <div v-if="$slots.action" class="sh-action">
      <slot name="action" />
    </div>
  </div>
</template>

<script setup>
defineProps({
  index: { type: String, default: '' },
  label: { type: String, default: '' },
  title: { type: String, default: '' },
  description: { type: String, default: '' },
  tone: { type: String, default: 'light' },
})
</script>

<style scoped>
.sh-wrap {
  display: flex;
  flex-wrap: wrap;
  align-items: flex-end;
  justify-content: space-between;
  gap: 40px 24px;
  margin-bottom: 48px;
}
.sh-left { max-width: 640px; }
.sh-meta {
  display: flex;
  align-items: center;
  gap: 12px;
}
.sh-idx {
  font-size: 12px;
  font-variant-numeric: tabular-nums;
  color: var(--muted, #7a6e63);
}
.sh-line {
  width: 24px;
  height: 1px;
  background: var(--line, #e7ded2);
}
.sh-lbl {
  font-size: 13px;
  font-weight: 500;
  color: var(--ink-soft, #3a322b);
}
.sh-lbl-dark { color: rgba(255,255,255,0.5); }
.sh-title {
  margin-top: 16px;
  font-family: var(--ref-font-display);
  font-size: clamp(28px, 3.4vw, 42px);
  font-weight: 400;
  line-height: 1.15;
  letter-spacing: -0.045em;
  text-wrap: balance;
  color: var(--ink, #17130f);
}
.sh-title-dark { color: var(--cream, #f5efe7); }
.sh-desc {
  margin-top: 16px;
  max-width: 560px;
  font-size: 15px;
  line-height: 1.65;
  color: var(--ink-soft, #3a322b);
  opacity: 0.8;
}
.sh-desc-dark { color: rgba(255,255,255,0.55); }
.sh-action { padding-bottom: 4px; flex-shrink: 0; }

@media (max-width: 720px) {
  .sh-wrap { display: block; margin-bottom: 24px; }
  .sh-title { font-size: 28px; }
  .sh-desc { margin-top: 12px; }
  .sh-action { margin-top: 12px; }
}
</style>
