// frontend/src/components/common/Reveal.vue
<template>
  <component
    :is="tag"
    ref="el"
    class="rvl"
    :class="{ 'rvl-in': visible }"
    :style="{
      transitionDelay: transitionDelay,
      '--rvl-y': `${props.y}px`,
      '--rvl-blur': props.blur ? '6px' : '0px',
    }"
  >
    <slot />
  </component>
</template>

<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue'

const props = defineProps({
  /** 渲染的标签（div / span ...）。 */
  tag: { type: String, default: 'div' },
  /** 秒。配合 index * 0.05 可做分组错落。 */
  delay: { type: Number, default: 0 },
  /** 进入前的垂直偏移（px）。 */
  y: { type: Number, default: 18 },
  /** 进入前是否附加 6px 微模糊。 */
  blur: { type: Boolean, default: true },
  /** 是否只播放一次。 */
  once: { type: Boolean, default: true },
})

const el = ref(null)
const visible = ref(false)

const EASE = 'cubic-bezier(0.23, 1, 0.32, 1)'
const transitionDelay = props.delay ? `${props.delay}s` : undefined

let observer = null

function reduceMotion() {
  return typeof window !== 'undefined'
    && window.matchMedia?.('(prefers-reduced-motion: reduce)').matches
}

onMounted(() => {
  if (reduceMotion()) {
    visible.value = true
    return
  }
  if (!('IntersectionObserver' in window)) {
    visible.value = true
    return
  }
  observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          visible.value = true
          if (props.once && observer) {
            observer.unobserve(entry.target)
            observer.disconnect()
          }
        } else if (!props.once) {
          visible.value = false
        }
      })
    },
    { rootMargin: '-10% 0px -12% 0px', threshold: 0 },
  )
  if (el.value) observer.observe(el.value)
})

onBeforeUnmount(() => {
  if (observer) observer.disconnect()
})
</script>

<style scoped>
.rvl {
  display: block;
  opacity: 0;
  transform: translateY(var(--rvl-y, 18px));
  filter: blur(var(--rvl-blur, 6px));
  transition:
    opacity 0.3s var(--rvl-ease, cubic-bezier(0.23, 1, 0.32, 1)),
    transform 0.3s var(--rvl-ease, cubic-bezier(0.23, 1, 0.32, 1)),
    filter 0.3s var(--rvl-ease, cubic-bezier(0.23, 1, 0.32, 1));
  will-change: opacity, transform, filter;
}
.rvl-in {
  opacity: 1;
  transform: translateY(0);
  filter: blur(0);
}
</style>

// 设计语言/src/components/Reveal/index.tsx
import React, { useEffect, useRef, useState } from 'react';

const EASE = 'cubic-bezier(0.23, 1, 0.32, 1)';

export interface RevealProps {
  /** Rendered tag (div / span / li ...). */
  tag?: keyof React.JSX.IntrinsicElements;
  /** Seconds. Combine with `index * 0.05` for staggered groups. */
  delay?: number;
  /** Vertical offset before entering (px). */
  y?: number;
  /** Whether a 6px micro-blur is applied before entering. */
  blur?: boolean;
  /** Whether the reveal plays only once. */
  once?: boolean;
  className?: string;
  style?: React.CSSProperties;
  children?: React.ReactNode;
}

function reduceMotion(): boolean {
  return (
    typeof window !== 'undefined' &&
    !!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches);

}

export function Reveal({
  tag = 'div',
  delay = 0,
  y = 18,
  blur = true,
  once = true,
  className,
  style,
  children
}: RevealProps) {
  const el = useRef<HTMLElement | null>(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    if (reduceMotion()) {
      setVisible(true);
      return;
    }
    if (!('IntersectionObserver' in window)) {
      setVisible(true);
      return;
    }

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setVisible(true);
            if (once) {
              observer.unobserve(entry.target);
              observer.disconnect();
            }
          } else if (!once) {
            setVisible(false);
          }
        });
      },
      { rootMargin: '-10% 0px -12% 0px', threshold: 0 }
    );

    if (el.current) observer.observe(el.current);

    return () => observer.disconnect();
  }, [once]);

  const Tag = tag as unknown as React.ElementType;

  return (
    <Tag
      ref={el}
      className={className}
      style={{
        display: 'block',
        opacity: visible ? 1 : 0,
        transform: visible ? 'translateY(0)' : `translateY(${y}px)`,
        filter: visible ? 'blur(0)' : `blur(${blur ? 6 : 0}px)`,
        transition: `opacity 0.3s ${EASE}, transform 0.3s ${EASE}, filter 0.3s ${EASE}`,
        transitionDelay: delay ? `${delay}s` : undefined,
        willChange: 'opacity, transform, filter',
        ...style
      }}>
      
      {children}
    </Tag>);

}
