// frontend/src/components/pet/PetList.vue
<template>
  <ul class="pet-grid">
    <li v-for="pet in pets" :key="pet.id_wsh" class="pet-card-wrap">
      <article class="pet-card" @click="$emit('view', pet.id_wsh)">
        <!-- Header: Avatar + Name -->
        <header class="pet-card-header">
          <div class="pet-avatar-wrap">
            <img
              v-if="pet.avatar_wsh"
              class="pet-avatar-img"
              :src="pet.avatar_wsh"
              :alt="pet.name_wsh"
              loading="lazy"
            >
            <span v-else class="pet-avatar-placeholder" :aria-label="`${pet.name_wsh}（${petTypeLabel(pet.type_wsh)}）暂无头像`">
              <svg v-if="normalizeType(pet.type_wsh) === 'dog'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M10 5.172C10 3.782 8.423 2.679 6.5 3c-2.823.47-4.113 6.006-4 7 .08.703 1.725 1.722 3.656 1 1.261-.472 1.96-1.45 2.344-2.5M14.267 5.172c0-1.39 1.577-2.493 3.5-2.172 2.823.47 4.113 6.006 4 7-.08.703-1.725 1.722-3.656 1-1.261-.472-1.855-1.45-2.239-2.5M8 14v.5M15.5 14v.5M11.75 16.25c.75.5 2 .5 2.75 0M4.42 11.247A13.152 13.152 0 0 0 4 14.556C4 18.728 7.582 21 12 21s8-2.272 8-6.444c0-1.061-.162-2.2-.493-3.309m-9.243-6.082A8.801 8.801 0 0 1 12 5c.78 0 1.5.108 2.161.306"/></svg>
              <svg v-else-if="normalizeType(pet.type_wsh) === 'cat'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M12 5c-1.5-3-5-3-5-3s0 3.5 1.5 5M12 5c1.5-3 5-3 5-3s0 3.5-1.5 5M12 5v14M8 19c-2 0-4-1-4-3 0-2 2-3 4-3M16 19c2 0 4-1 4-3 0-2-2-3-4-3M8 19h8"/></svg>
              <svg v-else-if="normalizeType(pet.type_wsh) === 'rabbit'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M8 2c0 2-2 6-2 10 0 3 2 6 6 6s6-3 6-6c0-4-2-8-2-10M12 18v4M9 22h6"/></svg>
              <svg v-else viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M11.5 9C11.5 9 9 7 7 9s-2 5 2 7 7-2 7-2-1.5-2-4.5-4z"/><circle cx="6.5" cy="6.5" r="1.5"/><circle cx="17.5" cy="6.5" r="1.5"/><circle cx="11.5" cy="5.5" r="1.5"/><path d="M12 18c-4 0-6-2-6-5 0-2 2-4 6-4s6 2 6 4c0 3-2 5-6 5z"/></svg>
            </span>
          </div>
          <div class="pet-title">
            <div class="pet-name-row">
              <button type="button" class="pet-name-btn" @click.stop="$emit('view', pet.id_wsh)">
                {{ pet.name_wsh }}
              </button>
              <svg class="pet-arrow-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M7 17L17 7M17 7H7M17 7v10"/></svg>
            </div>
            <p class="pet-type-breed">
              {{ petTypeLabel(pet.type_wsh) }}
              <span class="pet-sep">·</span>
              {{ pet.breed_wsh || '未知品种' }}
            </p>
          </div>
          <span v-if="!profileComplete(pet)" class="pet-badge-warn">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
            档案待完善
          </span>
        </header>

        <!-- Specs Grid -->
        <dl class="pet-specs">
          <div class="pet-spec">
            <dt>年龄</dt>
            <dd :class="{ 'pet-spec-empty': !formatAge(pet.age_wsh) }">
              {{ formatAge(pet.age_wsh) || '—' }}
            </dd>
          </div>
          <div class="pet-spec">
            <dt>体重</dt>
            <dd :class="{ 'pet-spec-empty': !formatWeight(pet.weight_wsh) }">
              {{ formatWeight(pet.weight_wsh) || '—' }}
            </dd>
          </div>
          <div class="pet-spec">
            <dt>性别</dt>
            <dd :class="{ 'pet-spec-empty': pet.gender_wsh === 0 }">
              {{ genderLabel(pet.gender_wsh) }}
            </dd>
          </div>
        </dl>

        <!-- Health Flags -->
        <ul class="pet-health">
          <li class="pet-health-item" :class="{ active: pet.vaccinated_wsh === 1 }">
            <span class="pet-dot" :class="pet.vaccinated_wsh === 1 ? 'dot-ok' : 'dot-muted'"></span>
            {{ pet.vaccinated_wsh === 1 ? '已免疫' : '未免疫' }}
          </li>
          <li class="pet-health-item" :class="{ active: pet.sterilized_wsh === 1 }">
            <span class="pet-dot" :class="pet.sterilized_wsh === 1 ? 'dot-info' : 'dot-muted'"></span>
            {{ pet.sterilized_wsh === 1 ? '已绝育' : '未绝育' }}
          </li>
        </ul>

        <!-- Notes -->
        <div v-if="pet.description_wsh || pet.allergies_wsh || pet.habits_wsh" class="pet-notes">
          <p v-if="pet.description_wsh" class="pet-note-desc">{{ pet.description_wsh }}</p>
          <p v-if="pet.habits_wsh" class="pet-note-habit">
            <span class="pet-note-label">习惯</span> {{ pet.habits_wsh }}
          </p>
          <p v-if="pet.allergies_wsh" class="pet-note-allergy">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
            <span>
              <strong>过敏 / 禁忌</strong> {{ pet.allergies_wsh }}
            </span>
          </p>
        </div>

        <!-- Actions -->
        <div class="pet-actions" @click.stop>
          <button class="btn btn-primary btn-sm" @click="$emit('view', pet.id_wsh)">查看档案</button>
          <button class="btn btn-outline btn-sm" @click="$emit('edit', pet)">编辑</button>
          <button class="btn btn-quiet btn-sm pet-delete-btn" @click="$emit('delete', pet.id_wsh)" :aria-label="`删除 ${pet.name_wsh}`">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>
            删除
          </button>
        </div>
      </article>
    </li>
  </ul>
</template>

<script setup>
defineProps({
  pets: { type: Array, required: true },
})

defineEmits(['edit', 'delete', 'view'])

const typeMap = {
  dog: '狗', cat: '猫', rabbit: '兔子', bird: '鸟',
  fish: '鱼', hamster: '仓鼠', other: '其他',
}

function normalizeType(type) {
  return String(type || 'other').toLowerCase()
}

function petTypeLabel(type) {
  return typeMap[normalizeType(type)] || type || '其他'
}

function genderLabel(gender) {
  const value = Number(gender)
  return value === 1 ? '公' : value === 2 ? '母' : '未知'
}

function formatAge(age) {
  return age ? `${age} 个月` : null
}

function formatWeight(weight) {
  return weight ? `${weight} kg` : null
}

function profileComplete(pet) {
  return Boolean(pet.description_wsh)
}
</script>

<style scoped>
.pet-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 20px;
}
@media (min-width: 768px) {
  .pet-grid { grid-template-columns: repeat(2, 1fr); }
}
@media (min-width: 1200px) {
  .pet-grid { grid-template-columns: repeat(3, 1fr); }
}

.pet-card-wrap { height: 100%; }

.pet-card {
  display: flex;
  flex-direction: column;
  height: 100%;
  padding: 20px;
  border-radius: 16px;
  border: 1px solid var(--color-border);
  background: var(--color-card);
  box-shadow: var(--shadow-sm);
  cursor: pointer;
  transition: border-color 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease;
}
.pet-card:hover {
  border-color: var(--color-border);
  box-shadow: var(--shadow-md);
  transform: translateY(-2px);
}

/* Header */
.pet-card-header {
  display: flex;
  align-items: flex-start;
  gap: 14px;
}
.pet-avatar-wrap { flex-shrink: 0; }
.pet-avatar-img {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  object-fit: cover;
  border: 1px solid var(--color-border);
}
.pet-avatar-placeholder {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: var(--color-muted);
  color: var(--color-muted-foreground);
  border: 1px solid var(--color-border);
}
.pet-avatar-placeholder svg { width: 24px; height: 24px; }

.pet-title { min-width: 0; flex: 1; }
.pet-name-row {
  display: flex;
  align-items: center;
  gap: 6px;
}
.pet-name-btn {
  background: none;
  border: none;
  padding: 0;
  font-size: 16px;
  font-weight: 600;
  color: var(--color-foreground);
  text-align: left;
  cursor: pointer;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  border-radius: 4px;
}
.pet-name-btn:hover { text-decoration: underline; }
.pet-name-btn:focus-visible {
  outline: 2px solid var(--color-ring);
  outline-offset: 2px;
}
.pet-arrow-icon {
  width: 14px;
  height: 14px;
  color: var(--color-muted-foreground);
  opacity: 0;
  transition: opacity 0.2s ease;
  flex-shrink: 0;
}
.pet-card:hover .pet-arrow-icon { opacity: 1; }
.pet-type-breed {
  margin-top: 2px;
  font-size: 14px;
  color: var(--color-muted-foreground);
}
.pet-sep { margin: 0 6px; color: var(--color-border); }

.pet-badge-warn {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  flex-shrink: 0;
  padding: 4px 10px;
  border-radius: 999px;
  background: rgba(249, 115, 22, 0.08);
  font-size: 12px;
  font-weight: 500;
  color: var(--color-primary);
}
.pet-badge-warn svg { width: 12px; height: 12px; }

/* Specs */
.pet-specs {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 0;
  margin: 16px 0;
  padding: 14px 0;
  border-top: 1px solid var(--color-border);
  border-bottom: 1px solid var(--color-border);
}
.pet-spec {
  padding: 0 16px;
  border-right: 1px solid var(--color-border);
}
.pet-spec:first-child { padding-left: 0; }
.pet-spec:last-child { border-right: none; padding-right: 0; }
.pet-spec dt {
  font-size: 11px;
  font-weight: 500;
  letter-spacing: 0.05em;
  color: var(--color-muted-foreground);
  text-transform: uppercase;
}
.pet-spec dd {
  margin-top: 4px;
  font-size: 14px;
  font-weight: 600;
  color: var(--color-foreground);
  font-variant-numeric: tabular-nums;
}
.pet-spec dd.pet-spec-empty { color: var(--color-muted-foreground); }

/* Health Flags */
.pet-health {
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
  list-style: none;
  margin-bottom: 0;
}
.pet-health-item {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  color: var(--color-muted-foreground);
}
.pet-health-item.active { color: var(--color-foreground); }
.pet-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
}
.dot-ok { background: var(--color-success); }
.dot-info { background: var(--color-info); }
.dot-muted { background: var(--color-border); }

/* Notes */
.pet-notes { margin-top: 12px; flex: 1; }
.pet-note-desc {
  font-size: 14px;
  line-height: 1.6;
  color: var(--color-muted-foreground);
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.pet-note-habit {
  margin-top: 6px;
  font-size: 14px;
  line-height: 1.6;
  color: var(--color-muted-foreground);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.pet-note-label { color: var(--color-muted-foreground); }
.pet-note-allergy {
  display: flex;
  align-items: flex-start;
  gap: 6px;
  margin-top: 6px;
  font-size: 14px;
  line-height: 1.6;
  color: var(--color-danger);
}
.pet-note-allergy svg {
  width: 14px;
  height: 14px;
  flex-shrink: 0;
  margin-top: 3px;
}
.pet-note-allergy strong { font-weight: 500; }

/* Actions */
.pet-actions {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 16px;
}
.pet-delete-btn {
  margin-left: auto;
  padding: 8px 10px;
}
.pet-delete-btn svg { width: 14px; height: 14px; }

/* Quiet Button */
.btn-quiet {
  background: transparent;
  border: none;
  color: var(--color-muted-foreground);
  cursor: pointer;
}
.btn-quiet:hover {
  background: rgba(220, 38, 38, 0.06);
  color: var(--color-danger);
}
</style>

// 设计语言/src/components/PetList/index.tsx
import React from 'react';
import {
  AlertTriangleIcon,
  ArrowUpRightIcon,
  ClockIcon,
  PawPrintIcon,
  Trash2Icon } from
'lucide-react';

/* -------------------------------------------------------------------------
 * Types — field names preserved 1:1 from the Vue source (`*_wsh` suffixes).
 * ---------------------------------------------------------------------- */

export type PetType =
'dog' |
'cat' |
'rabbit' |
'bird' |
'fish' |
'hamster' |
'other' |
string;

export interface Pet {
  id_wsh: string | number;
  name_wsh: string;
  type_wsh?: PetType;
  breed_wsh?: string | null;
  avatar_wsh?: string | null;
  age_wsh?: number | string | null;
  weight_wsh?: number | string | null;
  /** 0 未知 · 1 公 · 2 母 */
  gender_wsh?: number | null;
  /** 1 = 已免疫 */
  vaccinated_wsh?: number | null;
  /** 1 = 已绝育 */
  sterilized_wsh?: number | null;
  description_wsh?: string | null;
  habits_wsh?: string | null;
  allergies_wsh?: string | null;
}

export interface PetListProps {
  /** Pet roster to render. */
  pets: Pet[];
  /** Fired when a card, the pet name, or 查看档案 is activated. */
  onView?: (id: Pet['id_wsh']) => void;
  /** Fired with the full pet record when 编辑 is activated. */
  onEdit?: (pet: Pet) => void;
  /** Fired when 删除 is activated. */
  onDelete?: (id: Pet['id_wsh']) => void;
  /** Replaces the grid with a skeleton placeholder set. */
  loading?: boolean;
  /** Rendered when `pets` is empty and not loading. */
  emptyAction?: React.ReactNode;
  className?: string;
}

/* -------------------------------------------------------------------------
 * Component
 * ---------------------------------------------------------------------- */

export function PetList({
  pets,
  onView,
  onEdit,
  onDelete,
  loading = false,
  emptyAction,
  className = ''
}: PetListProps) {
  if (loading) {
    return (
      <div
        className={`grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3 ${className}`}
        aria-busy="true"
        aria-live="polite">
        
        {[0, 1, 2].map((key) =>
        <PetCardSkeleton key={key} />
        )}
      </div>);

  }

  if (!pets.length) {
    return (
      <div
        className={`rounded-card border border-line bg-surface px-6 py-14 text-center ${className}`}>
        
        <span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-sand text-muted">
          <PawPrintIcon className="h-5 w-5" aria-hidden="true" />
        </span>
        <h3 className="mt-4 font-display text-display-xs text-ink">暂无宠物档案</h3>
        <p className="mx-auto mt-2 max-w-prose text-meta text-ink-soft">
          添加宠物后，服务人员可以提前了解它的品种、健康与忌口情况。
        </p>
        {emptyAction ? <div className="mt-5">{emptyAction}</div> : null}
      </div>);

  }

  return (
    <ul
      className={`grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3 ${className}`}>
      
      {pets.map((pet) =>
      <li key={pet.id_wsh} className="h-full">
          <article
          onClick={() => onView?.(pet.id_wsh)}
          className="group flex h-full cursor-pointer flex-col rounded-card border border-line bg-surface p-5 transition-all duration-normal ease-editorial hover:-translate-y-1 hover:border-brand/40 hover:shadow-lift">
          
            {/* Header: Avatar + Name */}
            <header className="flex items-start gap-3.5">
              <div className="shrink-0">
                {pet.avatar_wsh ?
              <img
                className="h-14 w-14 rounded-full border border-line object-cover"
                src={pet.avatar_wsh}
                alt={pet.name_wsh}
                loading="lazy" /> :


              <span
                className="flex h-14 w-14 items-center justify-center rounded-full border border-line bg-sand text-muted"
                aria-label={`${pet.name_wsh}（${petTypeLabel(
                  pet.type_wsh
                )}）暂无头像`}>
                
                    <PetTypeGlyph type={pet.type_wsh} />
                  </span>
              }
              </div>

              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-1.5">
                  <button
                  type="button"
                  onClick={(event) => {
                    event.stopPropagation();
                    onView?.(pet.id_wsh);
                  }}
                  className="ref-truncate rounded-[4px] text-left text-[16px] font-semibold text-ink hover:underline">
                  
                    {pet.name_wsh}
                  </button>
                  <ArrowUpRightIcon
                  className="h-3.5 w-3.5 shrink-0 text-muted opacity-0 transition-opacity duration-normal ease-editorial group-hover:opacity-100"
                  aria-hidden="true" />
                
                </div>
                <p className="mt-0.5 text-[14px] text-muted">
                  {petTypeLabel(pet.type_wsh)}
                  <span className="mx-1.5 text-line">·</span>
                  {pet.breed_wsh || '未知品种'}
                </p>
              </div>

              {!profileComplete(pet) &&
            <span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-brand/10 px-2.5 py-1 text-[12px] font-medium text-brand">
                  <ClockIcon className="h-3 w-3" aria-hidden="true" />
                  档案待完善
                </span>
            }
            </header>

            {/* Specs */}
            <dl className="my-4 grid grid-cols-3 border-y border-line py-3.5">
              <Spec label="年龄" value={formatAge(pet.age_wsh)} />
              <Spec label="体重" value={formatWeight(pet.weight_wsh)} />
              <Spec
              label="性别"
              value={genderLabel(pet.gender_wsh)}
              muted={Number(pet.gender_wsh) === 0 || pet.gender_wsh == null} />
            
            </dl>

            {/* Health flags */}
            <ul className="flex flex-wrap gap-5">
              <HealthFlag
              active={pet.vaccinated_wsh === 1}
              tone="positive"
              label={pet.vaccinated_wsh === 1 ? '已免疫' : '未免疫'} />
            
              <HealthFlag
              active={pet.sterilized_wsh === 1}
              tone="informative"
              label={pet.sterilized_wsh === 1 ? '已绝育' : '未绝育'} />
            
            </ul>

            {/* Notes */}
            {(pet.description_wsh || pet.allergies_wsh || pet.habits_wsh) &&
          <div className="mt-3 flex-1">
                {pet.description_wsh &&
            <p className="ref-clamp-2 text-[14px] leading-relaxed text-ink-soft">
                    {pet.description_wsh}
                  </p>
            }
                {pet.habits_wsh &&
            <p className="ref-truncate mt-1.5 text-[14px] leading-relaxed text-muted">
                    <span className="text-muted">习惯</span> {pet.habits_wsh}
                  </p>
            }
                {pet.allergies_wsh &&
            <p className="mt-1.5 flex items-start gap-1.5 text-[14px] leading-relaxed text-critical">
                    <AlertTriangleIcon
                className="mt-1 h-3.5 w-3.5 shrink-0"
                aria-hidden="true" />
              
                    <span>
                      <strong className="font-medium">过敏 / 禁忌</strong>{' '}
                      {pet.allergies_wsh}
                    </span>
                  </p>
            }
              </div>
          }

            {/* Actions */}
            <div
            className="mt-4 flex items-center gap-2"
            onClick={(event) => event.stopPropagation()}>
            
              <button
              type="button"
              onClick={() => onView?.(pet.id_wsh)}
              className="rounded-control bg-brand px-3.5 py-2 text-control font-medium text-canvas transition-colors duration-fast ease-editorial hover:bg-brand-deep active:translate-y-px">
              
                查看档案
              </button>
              <button
              type="button"
              onClick={() => onEdit?.(pet)}
              className="rounded-control border border-line bg-surface px-3.5 py-2 text-control font-medium text-ink transition-colors duration-fast ease-editorial hover:border-brand hover:text-brand active:translate-y-px">
              
                编辑
              </button>
              <button
              type="button"
              onClick={() => onDelete?.(pet.id_wsh)}
              aria-label={`删除 ${pet.name_wsh}`}
              className="ml-auto inline-flex items-center gap-1.5 rounded-control px-2.5 py-2 text-control text-muted transition-colors duration-fast ease-editorial hover:bg-critical/[0.06] hover:text-critical">
              
                <Trash2Icon className="h-3.5 w-3.5" aria-hidden="true" />
                删除
              </button>
            </div>
          </article>
        </li>
      )}
    </ul>);

}

/* -------------------------------------------------------------------------
 * Internals
 * ---------------------------------------------------------------------- */

interface SpecProps {
  label: string;
  value: string | null;
  muted?: boolean;
}

function Spec({ label, value, muted = false }: SpecProps) {
  const isEmpty = muted || !value;
  return (
    <div className="border-r border-line px-4 first:pl-0 last:border-r-0 last:pr-0">
      <dt className="text-label font-medium uppercase text-muted">{label}</dt>
      <dd
        data-numeric="true"
        className={`mt-1 text-[14px] font-semibold ${
        isEmpty ? 'text-muted' : 'text-ink'}`
        }>
        
        {value || '—'}
      </dd>
    </div>);

}

interface HealthFlagProps {
  active: boolean;
  tone: 'positive' | 'informative';
  label: string;
}

function HealthFlag({ active, tone, label }: HealthFlagProps) {
  const dot = !active ?
  'bg-line' :
  tone === 'positive' ?
  'bg-positive' :
  'bg-informative';
  return (
    <li
      className={`inline-flex items-center gap-2 text-[14px] ${
      active ? 'text-ink' : 'text-muted'}`
      }>
      
      <span className={`h-1.5 w-1.5 rounded-full ${dot}`} aria-hidden="true" />
      {label}
    </li>);

}

function PetCardSkeleton() {
  return (
    <div className="flex h-full flex-col rounded-card border border-line bg-surface p-5">
      <div className="flex items-start gap-3.5">
        <div className="ref-shimmer h-14 w-14 rounded-full" />
        <div className="min-w-0 flex-1 space-y-2">
          <div className="ref-shimmer h-4 w-1/2 rounded-tile" />
          <div className="ref-shimmer h-3 w-3/4 rounded-tile" />
        </div>
      </div>
      <div className="my-4 grid grid-cols-3 gap-4 border-y border-line py-3.5">
        {[0, 1, 2].map((key) =>
        <div key={key} className="space-y-2">
            <div className="ref-shimmer h-2.5 w-10 rounded-tile" />
            <div className="ref-shimmer h-3.5 w-14 rounded-tile" />
          </div>
        )}
      </div>
      <div className="ref-shimmer h-3 w-full rounded-tile" />
      <div className="ref-shimmer mt-2 h-3 w-4/5 rounded-tile" />
      <div className="mt-4 flex gap-2">
        <div className="ref-shimmer h-9 w-24 rounded-control" />
        <div className="ref-shimmer h-9 w-16 rounded-control" />
      </div>
    </div>);

}

/** Species glyphs kept from the source markup (dog / cat / rabbit / paw). */
function PetTypeGlyph({ type }: {type?: PetType;}) {
  const normalized = normalizeType(type);
  const common = {
    viewBox: '0 0 24 24',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth: 1.5,
    className: 'h-6 w-6',
    'aria-hidden': true
  } as const;

  if (normalized === 'dog') {
    return (
      <svg {...common}>
        <path d="M10 5.172C10 3.782 8.423 2.679 6.5 3c-2.823.47-4.113 6.006-4 7 .08.703 1.725 1.722 3.656 1 1.261-.472 1.96-1.45 2.344-2.5M14.267 5.172c0-1.39 1.577-2.493 3.5-2.172 2.823.47 4.113 6.006 4 7-.08.703-1.725 1.722-3.656 1-1.261-.472-1.855-1.45-2.239-2.5M8 14v.5M15.5 14v.5M11.75 16.25c.75.5 2 .5 2.75 0M4.42 11.247A13.152 13.152 0 0 0 4 14.556C4 18.728 7.582 21 12 21s8-2.272 8-6.444c0-1.061-.162-2.2-.493-3.309m-9.243-6.082A8.801 8.801 0 0 1 12 5c.78 0 1.5.108 2.161.306" />
      </svg>);

  }
  if (normalized === 'cat') {
    return (
      <svg {...common}>
        <path d="M12 5c-1.5-3-5-3-5-3s0 3.5 1.5 5M12 5c1.5-3 5-3 5-3s0 3.5-1.5 5M12 5v14M8 19c-2 0-4-1-4-3 0-2 2-3 4-3M16 19c2 0 4-1 4-3 0-2-2-3-4-3M8 19h8" />
      </svg>);

  }
  if (normalized === 'rabbit') {
    return (
      <svg {...common}>
        <path d="M8 2c0 2-2 6-2 10 0 3 2 6 6 6s6-3 6-6c0-4-2-8-2-10M12 18v4M9 22h6" />
      </svg>);

  }
  return (
    <svg {...common}>
      <path d="M11.5 9C11.5 9 9 7 7 9s-2 5 2 7 7-2 7-2-1.5-2-4.5-4z" />
      <circle cx="6.5" cy="6.5" r="1.5" />
      <circle cx="17.5" cy="6.5" r="1.5" />
      <circle cx="11.5" cy="5.5" r="1.5" />
      <path d="M12 18c-4 0-6-2-6-5 0-2 2-4 6-4s6 2 6 4c0 3-2 5-6 5z" />
    </svg>);

}

/* -------------------------------------------------------------------------
 * Helpers — ported verbatim from the source script block
 * ---------------------------------------------------------------------- */

const typeMap: Record<string, string> = {
  dog: '狗',
  cat: '猫',
  rabbit: '兔子',
  bird: '鸟',
  fish: '鱼',
  hamster: '仓鼠',
  other: '其他'
};

export function normalizeType(type?: PetType): string {
  return String(type || 'other').toLowerCase();
}

export function petTypeLabel(type?: PetType): string {
  return typeMap[normalizeType(type)] || type || '其他';
}

export function genderLabel(gender?: number | null): string {
  const value = Number(gender);
  return value === 1 ? '公' : value === 2 ? '母' : '未知';
}

export function formatAge(age?: number | string | null): string | null {
  return age ? `${age} 个月` : null;
}

export function formatWeight(weight?: number | string | null): string | null {
  return weight ? `${weight} kg` : null;
}

export function profileComplete(pet: Pet): boolean {
  return Boolean(pet.description_wsh);
}
